### ISSUE TITLE
originalname and buffer aren't fetched

### ISSUE THREAD

**Issue by chakshujain** [olamilekan000/uploadit#3]
hello @olamilekan000 , I am getting internal server error when i am trying to hit post request with postman. I think the error is because of the variables originalname and buffer which you have initialized in helper.js . Please help.

**Comment by olamilekan000** [comment]
Check the multer configuration. is it pointing to "file"? and when making your request on Postman, is the name of the field "file"?

**Comment by aelaugh** [comment]
Hi @olamilekan000, I'm having the same issue. I made sure multer configuration is set to 'file' and postman field is also set to 'file'.  The app is able to get the 'originalname' from the file too.

**Comment by tuyenphk** [comment]
Have you guys figured out why we get the internal server error even though multer configuration is set to 'file' and the postman field is set to 'file' as well? @olamilekan000 @aelaugh @chakshujain

**Comment by olamilekan000** [comment]
Is "Form-Data" data selected on Postman? and also I'll appreciate if an Image of what your postman looks like can be shared.
